travis:
  secure:
    BINSTAR_TOKEN: z0V6FS87ue3iPXCGnaDQz2hwNvdMm0+b3r6mTHpnd3bczsMeVZPXOmcgpgm85o1vcvw50Ag6zjRg6ylY0CRliUqmfg1nPtMbDspHZBOkMIHXR5D0zlRCOkVRM3CV2P6tRE2icICv2ckm5kLusufDSwoxsrSrUc5dTOBhyfFA/WbD30rFd8G87nnR4OyODvJA3q9UjX+JYWNbErThSZnBhWvRRHXNUtT+F8kcHtTFaPGrBeqEfgY0W4WC03W5C2TouudgXLcCU1Dqc/3o3GOUFlny7nne0/iTEabsjSQN9OCwgondXd6NSHPWA/df5e8f1e2hdyNV7tquAgw5eNPYGuS4d2lfyC+eCkWKV+r3e7X/ELmO9nQXgh8FTWAuNgmhjs/+mORRwhDRn9gD5LOuVxY6lS1SriJS3LRvhJhTbFtdKzBCpS/bIXQclVq8IP92RA1g92EwImbvDgu433XpERY7Rg7Zs9OSwMg6r8EZlD/sePi9x/dFR/HmMVPxtzQ5c8QfqHU6ATvYR8kh3b5oXbbZ9ROgR0pEwdqlb9fJ0PQgkCaIVBKOzwQACxlhfHZbptKI7NzjuQiBiqYCj7ZQA1XPEZvzBN5K9kEJcDp3bTUmkgz0Ro6fk3VbXY3ROyG9YeCd8X22AraX8Ri3tOFDrV+BUxDui4pnj4m58F9OJ1U=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
